#Automaticly generating npm conda package
{% set data = load_npm() %}
package:
  name: {{data.get('name').lower()}}
  version: {{data.get('version')}}
build:
  number: {% block build_number %}10{% endblock %}
  script:
    - git clone "$RECIPE_DIR" 
    - npm --prefix "$PREFIX" install -g mountainlab-js --production
    - echo ls -lat "$PREFIX"/bin; ls -lat "$PREFIX"/bin
    - echo ls -lat "$PREFIX"/lib/node_modules; ls -lat "$PREFIX"/lib/node_modules
    - echo ls -lat "$PREFIX"/lib/node_modules/mountainlab-js; ls -lat "$PREFIX"/lib/node_modules/mountainlab-js
    - cd "$PREFIX"/lib/node_modules
    - PREV="$(readlink mountainlab-js)" bash -c 'rm mountainlab-js ; cp -a "$PREV" mountainlab-js'
    - echo ...after cp -a
    - echo ls -lat "$PREFIX"/lib/node_modules; ls -lat "$PREFIX"/lib/node_modules
    - echo ls -lat "$PREFIX"/lib/node_modules/mountainlab-js; ls -lat "$PREFIX"/lib/node_modules/mountainlab-js
    - du -sh mountainlab-js

requirements:
  build:
    - nodejs

  run:
    - nodejs

about:
  home: {{data.get('repository').get('url')}}
  license: {{data.get('license')}}

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
