# NOTE PACKAGE NAME (mountainlab) DOES NOT MATCH REPO NAME (mountainlab-js)
{% set npm = load_npm() %}
{% set build_script = npm.get('conda',{}).get('build_script',[]) %}
{% set test_commands = npm.get('conda',{}).get('test_commands',[]) %}
{% set pkg_name = npm.get('name') %}
{% set version = npm.get('version') %}
{% set build_number = npm.get('conda',{}).get('build_number',0) %}
{% set repo_url = npm.get('repository').get('url') %}
{% set license = npm.get('license') %}

package:
  name: {{ pkg_name|lower }}
  version: {{ version }}

source:
   url: {{ repo_url }}/archive/v{{ version }}.tar.gz

build:
  number: {{ build_number }}
  script:
    {% for line in build_script %}
      - {{ line }}
    {% endfor %}

requirements:
  host:
    - nodejs
  run:
    - nodejs
    - coreutils [ osx ]

test:
  commands:
    {% for line in test_commands %}
      - {{ line }}
    {% endfor %}
    #- npm list -g mountainlab
    #- ml-config
    #- ml-list-processors
  requires:
    - nodejs

about:
  home: {{ repo_url }}
  license: {{ license }}

