{% set data = load_npm() %}
package:
  name: {{data.get('name').lower()}}
  version: {{data.get('version')}}

source:
  git_url: .. # relative to recipe dir
  git_rev: HEAD

build:
  number: 2
  script:
    - tgzfile=$(npm pack)
    - npm install -g $tgzfile
    - mkdir -p "$PREFIX"/etc/conda/{de,}activate.d/
    - cp conda-recipe/mountainlab_activate.sh "$PREFIX"/etc/conda/activate.d/
    - cp conda-recipe/mountainlab_deactivate.sh "$PREFIX"/etc/conda/deactivate.d/

requirements:
  build:
    - nodejs

  run:
    - nodejs

test:
  commands:
    - npm list -g mountainlab-js
    - ml-config
  requires:
    - nodejs

about:
  home: {{data.get('repository').get('url')}}
  license: {{data.get('license')}}

# based on template at https://github.com/conda/conda-build/blob/master/conda_build/templates/npm.yaml